name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture
issue_tracker: https://github.com/icapps/flutter-icapps-architecture/issues
version: 2.2.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  computer: ^3.2.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^2.0.3

flutter: