name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture
issue_tracker: https://github.com/icapps/flutter-icapps-architecture/issues

version: 0.6.4

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  computer: ^3.0.0
  connectivity_plus: ^2.0.2
  device_info_plus: ^3.1.1
  dio: ^4.0.1
  flutter:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  connectivity_plus_platform_interface: ^1.1.0
  device_info_plus_platform_interface: ^2.2.1
  flutter_lints: ^1.0.4

flutter: